
# Experiment 5: Bidirectional Associative Memory (BAM)

## Aim
To implement Bidirectional Associative Memory (BAM) using two pairs of vectors.

## Objective
To understand hetero-associative memory and pattern recall.

## Theory
Bidirectional Associative Memory (BAM) is a type of recurrent neural network.

- It stores **pattern pairs (X, Y)**
- Given X → retrieves Y
- Given Y → retrieves X

This is called **hetero-associative memory**.

### Key Idea
Memory is stored as associations between two vectors.

### Weight Matrix:
W = Σ (Xᵀ * Y)

### Recall:
Y = sign(XW)  
X = sign(YWᵀ)


In [1]:

import numpy as np

# Define pattern pairs (from practical concept)
X = np.array([
    [1, 1, 1],
    [-1, -1, -1]
])

Y = np.array([
    [1, 1, 1, 1, 1, 1],
    [-1, -1, -1, -1, -1, -1]
])

print("Input Patterns (X):")
print(X)
print("\nTarget Patterns (Y):")
print(Y)


Input Patterns (X):
[[ 1  1  1]
 [-1 -1 -1]]

Target Patterns (Y):
[[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]]


## Step 1: Define Pattern Pairs

We need to define two sets of pattern vectors:
- **X (Input patterns)**: 3-dimensional binary vectors
- **Y (Target patterns)**: 6-dimensional binary vectors

These patterns represent the associations we want the BAM network to remember. In this case:
- Pattern 1: X₁ = [1, 1, 1] ↔ Y₁ = [1, 1, 1, 1, 1, 1]
- Pattern 2: X₂ = [-1, -1, -1] ↔ Y₂ = [-1, -1, -1, -1, -1, -1]

The network will learn to map X to Y and vice versa (bidirectional recall).


In [2]:

# Compute weight matrix
W = np.zeros((X.shape[1], Y.shape[1]))

for i in range(len(X)):
    W += np.outer(X[i], Y[i])

print("Weight Matrix:")
print(W)


Weight Matrix:
[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]


## Step 2: Compute the Weight Matrix

The weight matrix **W** stores all the associations between X and Y patterns. It is computed using the **outer product** formula:

$$W = \sum_{i=1}^{n} X_i^T \cdot Y_i$$

Where:
- For each pattern pair (Xᵢ, Yᵢ), we compute the outer product of Xᵢ and Yᵢ
- We sum all outer products to get the final weight matrix
- **W shape**: (3 × 6) because X has 3 dimensions and Y has 6 dimensions

This weight matrix encodes the bidirectional associations:
- When we multiply X by W, we get Y
- When we multiply Y by W^T, we get X


In [3]:

def sign(x):
    return np.where(x >= 0, 1, -1)


## Step 3: Define the Activation Function

We use the **sign function** (also called signum function) as the activation function:

$$\text{sign}(x) = \begin{cases} 1 & \text{if } x \geq 0 \\ -1 & \text{if } x < 0 \end{cases}$$

**Why use this function?**
- Converts continuous values from the dot product into binary bipolar values (1 or -1)
- Reflects the binary nature of the stored patterns
- Ensures outputs are valid patterns that can be compared with input patterns


In [4]:

# Test recall: X → Y
print("Forward Recall (X → Y):")

for i in range(len(X)):
    y_pred = sign(np.dot(X[i], W))
    print(f"Input: {X[i]} → Output: {y_pred}")


Forward Recall (X → Y):
Input: [1 1 1] → Output: [1 1 1 1 1 1]
Input: [-1 -1 -1] → Output: [-1 -1 -1 -1 -1 -1]


## Step 4: Test Forward Recall (X → Y)

Now we test if the network can retrieve Y patterns when given X patterns.

**Process:**
1. Take each input pattern X
2. Compute: Y_predicted = sign(X · W)
3. Compare the output with the stored Y patterns

**Expected Result:**
- When we input X₁ = [1, 1, 1], we should get back Y₁ = [1, 1, 1, 1, 1, 1]
- When we input X₂ = [-1, -1, -1], we should get back Y₂ = [-1, -1, -1, -1, -1, -1]

This demonstrates that the network correctly recalls the learned associations.


In [5]:

# Test recall: Y → X
print("\nBackward Recall (Y → X):")

for i in range(len(Y)):
    x_pred = sign(np.dot(Y[i], W.T))
    print(f"Input: {Y[i]} → Output: {x_pred}")



Backward Recall (Y → X):
Input: [1 1 1 1 1 1] → Output: [1 1 1]
Input: [-1 -1 -1 -1 -1 -1] → Output: [-1 -1 -1]


## Step 5: Test Backward Recall (Y → X)

This is the **bidirectional** part of BAM! We now test if the network can retrieve X patterns when given Y patterns.

**Process:**
1. Take each target pattern Y
2. Compute: X_predicted = sign(Y · W^T)
3. Note: We use W^T (transpose) because we're going in the reverse direction
4. Compare the output with the stored X patterns

**Expected Result:**
- When we input Y₁ = [1, 1, 1, 1, 1, 1], we should get back X₁ = [1, 1, 1]
- When we input Y₂ = [-1, -1, -1, -1, -1, -1], we should get back X₂ = [-1, -1, -1]

This demonstrates the **hetero-associative** nature of BAM: given an associated pattern from the other vector space, we can recall the original pattern.


## Summary & Key Takeaways

### What We Accomplished

1. **Pattern Storage**: We created a weight matrix W that encodes the associations between X and Y patterns using outer products.

2. **Forward Recall**: We successfully demonstrated that given any input X pattern, the network recalls the corresponding Y pattern using Y = sign(X · W).

3. **Backward Recall**: We demonstrated the bidirectional nature by showing that given any Y pattern, the network recalls the corresponding X pattern using X = sign(Y · W^T).

### How BAM Works

- **Storage Phase**: The outer product of pattern pairs builds up the weight matrix W
- **Recall Phase**: Multiplying an input by W (or W^T) produces an output that converges to a stored pattern
- **Bidirectionality**: Unlike unidirectional networks, BAM can recall in both directions

### Real-World Analogy

Think of it like a **face-name association**:
- Given a face (X), the network recalls the name (Y)
- Given a name (Y), the network recalls the face (X)

This bidirectional capability makes BAM useful for applications like **pattern completion, associative retrieval, and content-addressable memory**.

### Conclusion

We successfully implemented Bidirectional Associative Memory and demonstrated how it stores and retrieves pattern associations in both directions using matrix operations and activation functions.
