# Experiment 2: ANDNOT Function using McCulloch–Pitts Neural Net

## Aim
Generate the **ANDNOT** function using the **McCulloch–Pitts (MP) neural network**.

## Objective
To learn how to design an MP neuron for a logic function using fixed weights and a threshold.

## Reference
This notebook is based on the ANN practical sheet you uploaded. The practical specifies:
- weights: **w1 = 1**, **w2 = -1**
- threshold: **θ = 1**
- expected ANDNOT truth table output: **[0, 1, 0, 0]**

## Theory
The McCulloch–Pitts neuron is an early artificial neuron model that produces a **binary output**.

For two inputs \(x_1\) and \(x_2\), the net input is:

\[
Y_{in} = w_1 x_1 + w_2 x_2
\]

The output rule is:

\[
Y =
\begin{cases}
1, & Y_{in} \ge \theta \\
0, & Y_{in} < \theta
\end{cases}
\]

For this practical:

\[
w_1 = 1, \quad w_2 = -1, \quad \theta = 1
\]

So:

\[
Y_{in} = 1 \cdot x_1 + (-1) \cdot x_2 = x_1 - x_2
\]

This behaves like the **ANDNOT** function:
- output is 1 only when **x1 = 1** and **x2 = 0**


## Step 1: Define inputs, weights, and threshold

We use the truth table combinations of two binary inputs:

| X1 | X2 |
|----|----|
| 1  | 1  |
| 1  | 0  |
| 0  | 1  |
| 0  | 0  |

According to the practical:
- \(w_1 = 1\)
- \(w_2 = -1\)
- \(\theta = 1\)


In [3]:

import numpy as np

In [5]:
# Input combinations from the truth table
inputs = np.array([
    [1, 1],
    [1, 0],
    [0, 1],
    [0, 0]
])

# Fixed weights and threshold from the practical
w1 = 1
w2 = -1
theta = 1

weights = np.array([w1, w2])

print("Inputs:\n", inputs)
print("Weights:", weights)
print("Threshold:", theta)

Inputs:
 [[1 1]
 [1 0]
 [0 1]
 [0 0]]
Weights: [ 1 -1]
Threshold: 1


## Step 2: Create the MP neuron

The neuron computes:

\[
Y_{in} = w_1x_1 + w_2x_2
\]

Then it applies the threshold rule:

- if \(Y_{in} \ge \theta\), output = 1
- otherwise, output = 0


In [6]:
def mp_neuron(x, weights, theta):
    '''
    McCulloch-Pitts neuron for binary logic.

    Parameters:
    x : input vector [x1, x2]
    weights : array of weights [w1, w2]
    theta : threshold

    Returns:
    yin : net input
    y : binary output
    '''
    yin = np.dot(x, weights)   # compute net input
    y = 1 if yin >= theta else 0
    return yin, y

## Step 3: Apply the neuron to all input combinations

We now evaluate the ANDNOT truth table row by row and print:
- input values
- net input \(Y_{in}\)
- final output \(Y\)


In [7]:
results = []

print("X1 X2 | Yin | Y")
print("-" * 18)

for x in inputs:
    yin, y = mp_neuron(x, weights, theta)
    results.append([x[0], x[1], yin, y])
    print(f"{x[0]}  {x[1]}  |  {yin:>2}  | {y}")

X1 X2 | Yin | Y
------------------
1  1  |   0  | 0
1  0  |   1  | 1
0  1  |  -1  | 0
0  0  |   0  | 0


## Step 4: Verify the expected output

From the practical sheet, the expected output is:

\[
[0, 1, 0, 0]
\]

Let us extract the outputs from our program and compare them.


In [8]:
outputs = [row[3] for row in results]
expected_outputs = [0, 1, 0, 0]

print("Computed Output :", outputs)
print("Expected Output :", expected_outputs)

if outputs == expected_outputs:
    print("\nResult: The ANDNOT function is generated correctly.")
else:
    print("\nResult: The output does not match the expected truth table.")

Computed Output : [0, 1, 0, 0]
Expected Output : [0, 1, 0, 0]

Result: The ANDNOT function is generated correctly.


## Step 5: Show the result as a table

A tabular display makes the practical easier to understand and present.


In [9]:
# Display results in a clean NumPy array form
result_table = np.array(results, dtype=int)

print("Columns: [X1, X2, Yin, Y]")
print(result_table)

Columns: [X1, X2, Yin, Y]
[[ 1  1  0  0]
 [ 1  0  1  1]
 [ 0  1 -1  0]
 [ 0  0  0  0]]


## Explanation of Each Case

Using:

\[
Y_{in} = x_1 - x_2
\]

### Case 1: X1 = 1, X2 = 1
\[
Y_{in} = 1 - 1 = 0
\]
Since \(0 < 1\), output \(Y = 0\)

### Case 2: X1 = 1, X2 = 0
\[
Y_{in} = 1 - 0 = 1
\]
Since \(1 \ge 1\), output \(Y = 1\)

### Case 3: X1 = 0, X2 = 1
\[
Y_{in} = 0 - 1 = -1
\]
Since \(-1 < 1\), output \(Y = 0\)

### Case 4: X1 = 0, X2 = 0
\[
Y_{in} = 0 - 0 = 0
\]
Since \(0 < 1\), output \(Y = 0\)

Therefore, the final output is:

\[
[0, 1, 0, 0]
\]


## Conclusion

We successfully implemented the **ANDNOT** function using the **McCulloch–Pitts neural network**.

Using:
- **w1 = 1**
- **w2 = -1**
- **threshold = 1**

the neuron produced the output:

\[
[0, 1, 0, 0]
\]

which matches the required ANDNOT truth table.
